### ISSUE TITLE
Error when dragging game to newly created list

### ISSUE THREAD

**Issue by romancmx** [romancmx/switchlist#29]
Hey.. I created a new List.. tried to drag and drop a game to it.. and now it doesnt show me nothing..

Console error is:

TypeError: Cannot read property 'games' of null

at GameBoard.vue:92

at Array.filter (<anonymous>)

at s.isEmpty (GameBoard.vue:92)

at jt.get (vue.esm.js:3142)

at jt.evaluate (vue.esm.js:3249)

at s.isEmpty (vue.esm.js:3507)

at s.render (GameBoard.vue?d433:1)

at s.e._render (vue.esm.js:4544)

at s.<anonymous> (vue.esm.js:2788)

at jt.get (vue.esm.js:3142)

**Comment by Kvalevaag5** [comment]
Got the same issue last night (07/11/18).

**Comment by romancmx** [comment]
**tl;dr: this should be fixed now.**

There was a bug when dragging lists, `null` lists were being created in the database. I had to manually remove all those invalid lists from the database (from 50+ users 😢). Anyway, I ended up removing the list dragging functionality for now until it's solid. Feel free to give it another shot. I was able to reproduce both the bug and the fix.

Please confirm if still having same issue, (you may have to logout and login as list data is browser cached)
