### ISSUE TITLE
'Add your first game' gives empty side menu

### ISSUE THREAD

**Issue by Jdban** [romancmx/switchlist#48]
Screenshot: 

![image](https://user-images.githubusercontent.com/490005/42600262-8dcf81be-8516-11e8-8769-5348e07880f7.png)

**Comment by romancmx** [comment]
Fixed

![kapture 2018-08-08 at 14 11 06](https://user-images.githubusercontent.com/645310/43864612-fc0021ac-9b14-11e8-8d56-465b7ed7f804.gif)

**Comment by romancm** [comment]
@allcontributors please add @Jdban for bug
